/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          'SF Pro Text',
          'SF Pro Display',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      colors: {
        'surface-container-highest': '#dee3e9',
        primary: '#0064e0',
        'on-surface-variant': '#444950',
        'surface-variant': '#f1f4f7',
        outline: '#8595a4',
        'inverse-on-surface': '#ffffff',
        'on-primary-container': '#0a1317',
        'inverse-primary': '#0091ff',
        'outline-variant': '#dee3e9',
        'surface-container-high': '#eef2f6',
        tertiary: '#31a24c',
        'primary-fixed': '#e8f1ff',
        'tertiary-container': '#e8f7ed',
        'surface-tint': '#0064e0',
        secondary: '#a121ce',
        'on-error': '#ffffff',
        'primary-container': '#e8f1ff',
        'secondary-fixed': '#e9ddff',
        'error-container': '#ffe8ed',
        error: '#e41e3f',
        'on-error-container': '#9b1029',
        'surface-bright': '#ffffff',
        'surface-container-low': '#f1f4f7',
        'on-background': '#0a1317',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#0f3d1f',
        'primary-fixed-dim': '#d7e8ff',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container': '#f1f4f7',
        'on-primary-fixed-variant': '#0457cb',
        'on-secondary-fixed': '#23005c',
        'inverse-surface': '#0a1317',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#ced0d4',
        'on-tertiary': '#ffffff',
        'on-surface': '#0a1317',
        'on-primary-fixed': '#001a42',
        'tertiary-fixed': '#e8f7ed',
        'tertiary-fixed-dim': '#d3f0dd',
        'on-secondary-fixed-variant': '#5516be',
        'secondary-container': '#f3e8fb',
        surface: '#ffffff',
        'on-secondary-container': '#fffbff',
        background: '#fafafa',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#002113',
      },
      borderRadius: {
        DEFAULT: '0.375rem',
        lg: '0.5rem',
        xl: '1rem',
        '2xl': '1.5rem',
        '3xl': '2rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '280px',
        'stack-sm': '8px',
        'margin-desktop': '32px',
        gutter: '24px',
        'stack-md': '16px',
        'margin-mobile': '16px',
        'stack-lg': '24px',
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'title-md': ['18px', { lineHeight: '26px', letterSpacing: '-0.01em' }],
        'title-lg': ['20px', { lineHeight: '28px' }],
        'headline-md': ['24px', { lineHeight: '30px', letterSpacing: '-0.01em' }],
        'headline-lg': ['36px', { lineHeight: '46px', letterSpacing: '-0.015em' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em' }],
        code: ['14px', { lineHeight: '20px' }],
      },
    },
  },
  plugins: [],
}
