/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-highest': '#d3e4fe',
        primary: '#0058be',
        'on-surface-variant': '#424754',
        'surface-variant': '#d3e4fe',
        outline: '#727785',
        'inverse-on-surface': '#eaf1ff',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        'outline-variant': '#c2c6d6',
        'surface-container-high': '#dce9ff',
        tertiary: '#006947',
        'primary-fixed': '#d8e2ff',
        'tertiary-container': '#00855b',
        'surface-tint': '#005ac2',
        secondary: '#6b38d4',
        'on-error': '#ffffff',
        'primary-container': '#2170e4',
        'secondary-fixed': '#e9ddff',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'on-error-container': '#93000a',
        'surface-bright': '#f8f9ff',
        'surface-container-low': '#eff4ff',
        'on-background': '#0b1c30',
        'on-secondary': '#ffffff',
        'on-tertiary-container': '#f5fff6',
        'primary-fixed-dim': '#adc6ff',
        'secondary-fixed-dim': '#d0bcff',
        'surface-container': '#e5eeff',
        'on-primary-fixed-variant': '#004395',
        'on-secondary-fixed': '#23005c',
        'inverse-surface': '#213145',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'surface-dim': '#cbdbf5',
        'on-tertiary': '#ffffff',
        'on-surface': '#0b1c30',
        'on-primary-fixed': '#001a42',
        'tertiary-fixed': '#6ffbbe',
        'tertiary-fixed-dim': '#4edea3',
        'on-secondary-fixed-variant': '#5516be',
        'secondary-container': '#8455ef',
        surface: '#f8f9ff',
        'on-secondary-container': '#fffbff',
        background: '#f8f9ff',
        'on-tertiary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#002113',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'sidebar-width': '280px',
        'stack-sm': '8px',
        'margin-desktop': '32px',
        gutter: '24px',
        'stack-md': '16px',
        'margin-mobile': '16px',
        'stack-lg': '24px',
      },
      fontSize: {
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em' }],
        'body-md': ['14px', { lineHeight: '20px' }],
        'body-lg': ['16px', { lineHeight: '24px' }],
        'title-lg': ['20px', { lineHeight: '28px' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em' }],
        'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em' }],
        code: ['14px', { lineHeight: '20px' }],
      },
    },
  },
  plugins: [],
}
